### ISSUE TITLE
Add an example for Fourier analysis in dataproc.ipynb

### ISSUE THREAD

**Issue by daineseh** [yungyuc/first_day_with_python#1]
I think if audiences who most are not good at programming or engineering, and so on.
Maybe we can have a brief explanation about time domain and frequency domain in the practice?

**Comment by daineseh** [comment]
I think that is good idea，we might give it a try.

**Comment by yungyuc** [comment]
OK, I changed the title of this issue to track it.

**Comment by yungyuc** [comment]
@daineseh can you take a look at the current notes, and comment if there's still room to insert an example for Fourier analysis in [the second session (automation.ipynb)](automation.ipynb)?  Its two hours already have functions, conditionals, dictionary, and loop.

**Comment by daineseh** [comment]
Sure, I will do that later.

**Comment by yungyuc** [comment]
Any update?

**Comment by yungyuc** [comment]
We didn't have further discussions.  Close this issue.  Maybe we can do it in a future bootcamp.
