### ISSUE TITLE
Promotion words review

### ISSUE THREAD

**Issue by y3jo6** [yungyuc/first_day_with_python#19]
Python 是一門已經發展了29年的語言。最近跟當紅的人工智慧緊密的連結，更是讓它的熱度直線上升。
但你知道在科學分析的領域甚至在我們的國家同步輻射中心都有用 Python 來簡化他們的工作流程嗎？
為了讓大家稍稍領略Python的美好。
PyHUG 舉辦了為期一天的活動。從無到有的帶您建立一個 Python 程式。
歡迎沒有寫過任何程式的您加入～與我們一同體會 Python 的美好

活動資訊如下：
    時間：2018/12/8
    地點：交通大學工程三館xxxr教室
    < 地圖 >
    < 交通指引 >
    現場會準備電腦：環境是infuseai.io 
    感謝贊助商：infuseai.io, Effortless infrastructure for Machine Learning
    費用:免費

PyHUG ：
    新竹 Python 使用者群組

**Comment by y3jo6** [comment]
覺得哪裡不對，就直接改一版放上來 :) 。目標11/28發布在 PyHUG meetup/ JobSpace FB page.

**Comment by yungyuc** [comment]
I'd think something reading like a followup of the description in our event page (http://bit.ly/fdp1812) would be nice.  I also made a draft for your reference:

> Programming is hard, but also obsessively beautiful.  You can do so much with just some code typed into the computer.  Communication, analytics, prediction, and control can all be done by computers now.  Learning to code isn't an elective.  It's a must.
>
> But programming is an art, which always requires practices.  With proper guidance we can learn the skills very efficiently.  But when the guidance is absent, a lot of time is wasted.  Python Hsinchu user group (PyHUG) would like to offer help to those who don't know how to program.  We are a group of people who love coding in Python, and we'd like to host a bootcamp to show how to learn Python programming from ground zero.  The bootcamp is a day long.  You won’t learn everything about Python, but you will know the basic parts of it, finish a fun program, and make friends with a lot of people who can help you.

**Comment by y3jo6** [comment]
大家都說學寫程式不簡單，但是想一想你可以透過鍵盤就完成與他人溝通、分析與預測數據等等的事情，這是多麽有趣。隨著工業與環境與智能的結合。使用程式來幫助自己的工作與生活已經是必然的趨勢。學習的過程中總是需要練習。在練習寫程式的過程中有著適當的導引，我們可以學習的更有效率。特別是一群人一起學習，大家互相討論，會讓整個過程更加的有趣。

我們是新竹Python使用者社群。這次想利用一天的時間協助20個沒有寫過程式的人學習Python。沒有任何經驗、不是相關背景都沒關係。你會學到一些基礎的東西，可以完成一個有趣的小程式，來這裡跟我們還有其他夥伴交交朋友。當然如果你想更深入了解Python 我們也會很樂意協助你們。

**Comment by yungyuc** [comment]
Facebook page posted: https://www.facebook.com/jobspace/posts/2276331385980809
